### ISSUE TITLE
Local simulation to improve the speed of simulation.

### ISSUE THREAD

**Issue by Torbacka** [Albot-Online/Albot-Java-Library#2]
I would like to use local simulations to increase the speed of my algorithms. Because right now, a TCP call is made for each simulation step, creating a big overhead.

Would this be something you want in your Java library?

**Comment by JoeyOhman** [comment]
A local simulateMove would be great, feel free to add it! Otherwise I will try to make time to implement it myself soon. I am currently working on a local evaluateBoard, which I hope will do what you desired with the "killed" function. In combination with the local implementation of simulateMove.

**Comment by Torbacka** [comment]
Yeah that would be really nice to have. Sorry about the killed function, it was not supposed to be in that pull request. 

Then I will take a look at a local function of simulateMove. Think it will be a nice weekend project.

**Comment by JoeyOhman** [comment]
Well I used a slightly modified version of "killed" as a private function. :)

I implemented local simulateMove and getPossibleMoves along with the local evaluateBoard. They can be found in SnakeBoard. Sorry to steal your weekend project. :D
